BF_WipingConfig = {
    -- Have multiple per. e.g. toilet paper
    drainableWipeables = {
        ToiletPaper = { usesRequired = 4 }
    },

    -- Paper wipeables.
    -- category "paper_single" (newspapers, magazines, comics): shown as their own
    --   individual menu entry, one item = a full wipe.
    -- category "paper" (medium sheets tier 2, small scraps tier 4): pooled together
    --   into a single "Paper scraps" entry.
    -- category "grass": individual, capped at maxEfficiency.
    oneTimeWipeables = {
        Brochure = { usesRequired = 4, category = "paper" },
        BusinessCard = { usesRequired = 4, category = "paper" },
        BusinessCard_Nolans = { usesRequired = 4, category = "paper" },
        BusinessCard_Personal = { usesRequired = 4, category = "paper" },
        Catalog = { usesRequired = 4, category = "paper" },
        Doodle = { usesRequired = 4, category = "paper" },
        DoodleKids = { usesRequired = 4, category = "paper" },
        Flier = { usesRequired = 4, category = "paper" },
        Flier_Nolans = { usesRequired = 4, category = "paper" },
        GraphPaper = { usesRequired = 2, category = "paper" },
        HottieZ = { usesRequired = 1, category = "paper_single" },
        HottieZ_New = { usesRequired = 1, category = "paper_single" },
        IndexCard = { usesRequired = 2, category = "paper" },
        Magazine = { usesRequired = 1, category = "paper_single" },
        MagazineCrossword = { usesRequired = 1, category = "paper_single" },
        MagazineWordsearch = { usesRequired = 1, category = "paper_single" },
        Magazine_Art = { usesRequired = 1, category = "paper_single" },
        Magazine_Art_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Business = { usesRequired = 1, category = "paper_single" },
        Magazine_Business_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Car = { usesRequired = 1, category = "paper_single" },
        Magazine_Car_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Childs = { usesRequired = 1, category = "paper_single" },
        Magazine_Childs_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Cinema = { usesRequired = 1, category = "paper_single" },
        Magazine_Cinema_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Crime = { usesRequired = 1, category = "paper_single" },
        Magazine_Crime_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Fashion = { usesRequired = 1, category = "paper_single" },
        Magazine_Fashion_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Firearm = { usesRequired = 1, category = "paper_single" },
        Magazine_Firearm_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Gaming = { usesRequired = 1, category = "paper_single" },
        Magazine_Gaming_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Golf = { usesRequired = 1, category = "paper_single" },
        Magazine_Golf_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Health = { usesRequired = 1, category = "paper_single" },
        Magazine_Health_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Hobby = { usesRequired = 1, category = "paper_single" },
        Magazine_Hobby_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Horror = { usesRequired = 1, category = "paper_single" },
        Magazine_Horror_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Humor = { usesRequired = 1, category = "paper_single" },
        Magazine_Humor_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Military = { usesRequired = 1, category = "paper_single" },
        Magazine_Military_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Music = { usesRequired = 1, category = "paper_single" },
        Magazine_Music_New = { usesRequired = 1, category = "paper_single" },
        Magazine_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Outdoors = { usesRequired = 1, category = "paper_single" },
        Magazine_Outdoors_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Police = { usesRequired = 1, category = "paper_single" },
        Magazine_Police_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Popular = { usesRequired = 1, category = "paper_single" },
        Magazine_Popular_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Rich = { usesRequired = 1, category = "paper_single" },
        Magazine_Rich_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Science = { usesRequired = 1, category = "paper_single" },
        Magazine_Science_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Sports = { usesRequired = 1, category = "paper_single" },
        Magazine_Sports_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Tech = { usesRequired = 1, category = "paper_single" },
        Magazine_Tech_New = { usesRequired = 1, category = "paper_single" },
        Magazine_Teens = { usesRequired = 1, category = "paper_single" },
        Magazine_Teens_New = { usesRequired = 1, category = "paper_single" },
        Napkin = { usesRequired = 2, category = "paper" },
        Newspaper = { usesRequired = 1, category = "paper_single" },
        Newspaper_Dispatch_New = { usesRequired = 1, category = "paper_single" },
        Newspaper_Herald_New = { usesRequired = 1, category = "paper_single" },
        Newspaper_Knews_New = { usesRequired = 1, category = "paper_single" },
        Newspaper_New = { usesRequired = 1, category = "paper_single" },
        Newspaper_Recent = { usesRequired = 1, category = "paper_single" },
        Newspaper_Times_New = { usesRequired = 1, category = "paper_single" },
        Note = { usesRequired = 2, category = "paper" },
        PaperNapkins = { usesRequired = 2, category = "paper" },
        PaperTowel = { usesRequired = 2, category = "paper" },
        Paperwork = { usesRequired = 2, category = "paper" },
        Photo = { usesRequired = 4, category = "paper" },
        Photo_Hass = { usesRequired = 4, category = "paper" },
        Photo_Racy = { usesRequired = 4, category = "paper" },
        Photo_Secret = { usesRequired = 4, category = "paper" },
        Photo_VeryOld = { usesRequired = 4, category = "paper" },
        Postcard = { usesRequired = 4, category = "paper" },
        Receipt = { usesRequired = 4, category = "paper" },
        SheetPaper2 = { usesRequired = 2, category = "paper" },
        TVMagazine = { usesRequired = 1, category = "paper_single" },
        TVMagazine_New = { usesRequired = 1, category = "paper_single" },
        Tissue = { usesRequired = 2, category = "paper" },
        GrassTuft = { usesRequired = 3, category = "grass", maxEfficiency = 0.75 },
    },

    -- Cloth tools shown as individual menu entries. On DEFECATION they yield a
    -- soiled mod junk item; on URINATION they become a wet/dirty vanilla item.
    -- poopJunk   = item created (per use) when wiping after defecation
    -- poopCount  = how many junk items to create
    -- peeReplace = item the tool becomes when wiping after urination
    clothToolWipeables = {
        DishCloth  = { usesRequired = 1, poopJunk = "BF.RippedSheetsPooped", poopCount = 1, peeReplace = "Base.DishClothWet" },
        BathTowel  = { usesRequired = 1, poopJunk = "BF.RippedSheetsPooped", poopCount = 3, peeReplace = "Base.BathTowelWet" },
        RippedSheets = { usesRequired = 2, poopJunk = "BF.RippedSheetsPooped", poopCount = 1, peeReplace = "Base.RippedSheetsDirty" },
    },

    -- Books & multi-page paper (notebooks, diaries, journals): individual entries,
    -- one item = full wipe, returns clean SheetPaper2 pages plus dirty scraps.
    bookWipeables = {
        Book = { usesRequired = 10 },
        Book_AdventureNonFiction = { usesRequired = 10 },
        Book_Art = { usesRequired = 10 },
        Book_Baseball = { usesRequired = 10 },
        Book_Bible = { usesRequired = 10 },
        Book_Biography = { usesRequired = 10 },
        Book_Business = { usesRequired = 10 },
        Book_Childs = { usesRequired = 10 },
        Book_Cinema = { usesRequired = 10 },
        Book_Classic = { usesRequired = 10 },
        Book_ClassicFiction = { usesRequired = 10 },
        Book_ClassicNonfiction = { usesRequired = 10 },
        Book_Computer = { usesRequired = 10 },
        Book_CrimeFiction = { usesRequired = 10 },
        Book_Fantasy = { usesRequired = 10 },
        Book_Farming = { usesRequired = 10 },
        Book_Fashion = { usesRequired = 10 },
        Book_Fiction = { usesRequired = 10 },
        Book_GeneralNonFiction = { usesRequired = 10 },
        Book_GeneralReference = { usesRequired = 10 },
        Book_Golf = { usesRequired = 10 },
        Book_History = { usesRequired = 10 },
        Book_Horror = { usesRequired = 10 },
        Book_Legal = { usesRequired = 10 },
        Book_LiteraryFiction = { usesRequired = 10 },
        Book_Medical = { usesRequired = 10 },
        Book_Military = { usesRequired = 10 },
        Book_MilitaryHistory = { usesRequired = 10 },
        Book_Music = { usesRequired = 10 },
        Book_Nature = { usesRequired = 10 },
        Book_Occult = { usesRequired = 10 },
        Book_Philosophy = { usesRequired = 10 },
        Book_Policing = { usesRequired = 10 },
        Book_Politics = { usesRequired = 10 },
        Book_Quackery = { usesRequired = 10 },
        Book_Religion = { usesRequired = 10 },
        Book_Rich = { usesRequired = 10 },
        Book_Romance = { usesRequired = 10 },
        Book_SadNonFiction = { usesRequired = 10 },
        Book_SchoolTextbook = { usesRequired = 10 },
        Book_SciFi = { usesRequired = 10 },
        Book_Science = { usesRequired = 10 },
        Book_Sports = { usesRequired = 10 },
        Book_Thriller = { usesRequired = 10 },
        Book_Travel = { usesRequired = 10 },
        Book_Western = { usesRequired = 10 },
        ComicBook = { usesRequired = 10 },
        ComicBook_Retail = { usesRequired = 10 },
        Diary1 = { usesRequired = 10 },
        Diary2 = { usesRequired = 10 },
        Journal = { usesRequired = 10 },
        Notebook = { usesRequired = 10 },
        Notepad = { usesRequired = 10 },
        Paperback_AdventureNonFiction = { usesRequired = 10 },
        Paperback_Art = { usesRequired = 10 },
        Paperback_Baseball = { usesRequired = 10 },
        Paperback_Bible = { usesRequired = 10 },
        Paperback_Biography = { usesRequired = 10 },
        Paperback_Business = { usesRequired = 10 },
        Paperback_Childs = { usesRequired = 10 },
        Paperback_Cinema = { usesRequired = 10 },
        Paperback_Classic = { usesRequired = 10 },
        Paperback_ClassicFiction = { usesRequired = 10 },
        Paperback_ClassicNonfiction = { usesRequired = 10 },
        Paperback_Computer = { usesRequired = 10 },
        Paperback_Conspiracy = { usesRequired = 10 },
        Paperback_CrimeFiction = { usesRequired = 10 },
        Paperback_Diet = { usesRequired = 10 },
        Paperback_Fantasy = { usesRequired = 10 },
        Paperback_Fashion = { usesRequired = 10 },
        Paperback_Fiction = { usesRequired = 10 },
        Paperback_Golf = { usesRequired = 10 },
        Paperback_Hass = { usesRequired = 10 },
        Paperback_History = { usesRequired = 10 },
        Paperback_Horror = { usesRequired = 10 },
        Paperback_Legal = { usesRequired = 10 },
        Paperback_LiteraryFiction = { usesRequired = 10 },
        Paperback_Medical = { usesRequired = 10 },
        Paperback_Military = { usesRequired = 10 },
        Paperback_MilitaryHistory = { usesRequired = 10 },
        Paperback_Music = { usesRequired = 10 },
        Paperback_Nature = { usesRequired = 10 },
        Paperback_NewAge = { usesRequired = 10 },
        Paperback_Occult = { usesRequired = 10 },
        Paperback_Philosophy = { usesRequired = 10 },
        Paperback_Play = { usesRequired = 10 },
        Paperback_Policing = { usesRequired = 10 },
        Paperback_Politics = { usesRequired = 10 },
        Paperback_Poor = { usesRequired = 10 },
        Paperback_Quackery = { usesRequired = 10 },
        Paperback_Quigley = { usesRequired = 10 },
        Paperback_Relationship = { usesRequired = 10 },
        Paperback_Religion = { usesRequired = 10 },
        Paperback_Rich = { usesRequired = 10 },
        Paperback_Romance = { usesRequired = 10 },
        Paperback_SadNonFiction = { usesRequired = 10 },
        Paperback_Scary = { usesRequired = 10 },
        Paperback_SciFi = { usesRequired = 10 },
        Paperback_Science = { usesRequired = 10 },
        Paperback_SelfHelp = { usesRequired = 10 },
        Paperback_Sexy = { usesRequired = 10 },
        Paperback_Sports = { usesRequired = 10 },
        Paperback_Teens = { usesRequired = 10 },
        Paperback_Thriller = { usesRequired = 10 },
        Paperback_Travel = { usesRequired = 10 },
        Paperback_TrueCrime = { usesRequired = 10 },
        Paperback_Western = { usesRequired = 10 },
        PhotoBook = { usesRequired = 10 },
    }
}

-- Junk produced when wiping after DEFECATION (paper & books).
BF_WipeJunkMap = {
    ["Brochure"] = "BF.SheetPaper2Pooped",
    ["BusinessCard"] = "BF.SheetPaper2Pooped",
    ["BusinessCard_Nolans"] = "BF.SheetPaper2Pooped",
    ["BusinessCard_Personal"] = "BF.SheetPaper2Pooped",
    ["Catalog"] = "BF.SheetPaper2Pooped",
    ["Doodle"] = "BF.SheetPaper2Pooped",
    ["DoodleKids"] = "BF.SheetPaper2Pooped",
    ["Flier"] = "BF.SheetPaper2Pooped",
    ["Flier_Nolans"] = "BF.SheetPaper2Pooped",
    ["GraphPaper"] = "BF.GraphPaperPooped",
    ["HottieZ"] = "BF.HottieZPooped",
    ["HottieZ_New"] = "BF.HottieZPooped",
    ["IndexCard"] = "BF.SheetPaper2Pooped",
    ["Magazine"] = "BF.MagazinePooped",
    ["MagazineCrossword"] = "BF.MagazinePooped",
    ["MagazineWordsearch"] = "BF.MagazinePooped",
    ["Magazine_Art"] = "BF.MagazinePooped",
    ["Magazine_Art_New"] = "BF.MagazinePooped",
    ["Magazine_Business"] = "BF.MagazinePooped",
    ["Magazine_Business_New"] = "BF.MagazinePooped",
    ["Magazine_Car"] = "BF.MagazinePooped",
    ["Magazine_Car_New"] = "BF.MagazinePooped",
    ["Magazine_Childs"] = "BF.MagazinePooped",
    ["Magazine_Childs_New"] = "BF.MagazinePooped",
    ["Magazine_Cinema"] = "BF.MagazinePooped",
    ["Magazine_Cinema_New"] = "BF.MagazinePooped",
    ["Magazine_Crime"] = "BF.MagazinePooped",
    ["Magazine_Crime_New"] = "BF.MagazinePooped",
    ["Magazine_Fashion"] = "BF.MagazinePooped",
    ["Magazine_Fashion_New"] = "BF.MagazinePooped",
    ["Magazine_Firearm"] = "BF.MagazinePooped",
    ["Magazine_Firearm_New"] = "BF.MagazinePooped",
    ["Magazine_Gaming"] = "BF.MagazinePooped",
    ["Magazine_Gaming_New"] = "BF.MagazinePooped",
    ["Magazine_Golf"] = "BF.MagazinePooped",
    ["Magazine_Golf_New"] = "BF.MagazinePooped",
    ["Magazine_Health"] = "BF.MagazinePooped",
    ["Magazine_Health_New"] = "BF.MagazinePooped",
    ["Magazine_Hobby"] = "BF.MagazinePooped",
    ["Magazine_Hobby_New"] = "BF.MagazinePooped",
    ["Magazine_Horror"] = "BF.MagazinePooped",
    ["Magazine_Horror_New"] = "BF.MagazinePooped",
    ["Magazine_Humor"] = "BF.MagazinePooped",
    ["Magazine_Humor_New"] = "BF.MagazinePooped",
    ["Magazine_Military"] = "BF.MagazinePooped",
    ["Magazine_Military_New"] = "BF.MagazinePooped",
    ["Magazine_Music"] = "BF.MagazinePooped",
    ["Magazine_Music_New"] = "BF.MagazinePooped",
    ["Magazine_New"] = "BF.MagazinePooped",
    ["Magazine_Outdoors"] = "BF.MagazinePooped",
    ["Magazine_Outdoors_New"] = "BF.MagazinePooped",
    ["Magazine_Police"] = "BF.MagazinePooped",
    ["Magazine_Police_New"] = "BF.MagazinePooped",
    ["Magazine_Popular"] = "BF.MagazinePooped",
    ["Magazine_Popular_New"] = "BF.MagazinePooped",
    ["Magazine_Rich"] = "BF.MagazinePooped",
    ["Magazine_Rich_New"] = "BF.MagazinePooped",
    ["Magazine_Science"] = "BF.MagazinePooped",
    ["Magazine_Science_New"] = "BF.MagazinePooped",
    ["Magazine_Sports"] = "BF.MagazinePooped",
    ["Magazine_Sports_New"] = "BF.MagazinePooped",
    ["Magazine_Tech"] = "BF.MagazinePooped",
    ["Magazine_Tech_New"] = "BF.MagazinePooped",
    ["Magazine_Teens"] = "BF.MagazinePooped",
    ["Magazine_Teens_New"] = "BF.MagazinePooped",
    ["Napkin"] = "BF.SheetPaper2Pooped",
    ["Newspaper"] = "BF.NewspaperPooped",
    ["Newspaper_Dispatch_New"] = "BF.NewspaperPooped",
    ["Newspaper_Herald_New"] = "BF.NewspaperPooped",
    ["Newspaper_Knews_New"] = "BF.NewspaperPooped",
    ["Newspaper_New"] = "BF.NewspaperPooped",
    ["Newspaper_Recent"] = "BF.NewspaperPooped",
    ["Newspaper_Times_New"] = "BF.NewspaperPooped",
    ["Note"] = "BF.SheetPaper2Pooped",
    ["PaperNapkins"] = "BF.SheetPaper2Pooped",
    ["PaperTowel"] = "BF.SheetPaper2Pooped",
    ["Paperwork"] = "BF.PaperworkPooped",
    ["Photo"] = "BF.SheetPaper2Pooped",
    ["Photo_Hass"] = "BF.SheetPaper2Pooped",
    ["Photo_Racy"] = "BF.SheetPaper2Pooped",
    ["Photo_Secret"] = "BF.SheetPaper2Pooped",
    ["Photo_VeryOld"] = "BF.SheetPaper2Pooped",
    ["Postcard"] = "BF.SheetPaper2Pooped",
    ["Receipt"] = "BF.ReceiptPooped",
    ["SheetPaper2"] = "BF.SheetPaper2Pooped",
    ["TVMagazine"] = "BF.MagazinePooped",
    ["TVMagazine_New"] = "BF.MagazinePooped",
    ["Tissue"] = "BF.TissuePooped",
    ["GrassTuft"] = "BF.GrassTuftPooped",
    ["Book"] = "BF.SheetPaper2Pooped",
    ["Book_AdventureNonFiction"] = "BF.SheetPaper2Pooped",
    ["Book_Art"] = "BF.SheetPaper2Pooped",
    ["Book_Baseball"] = "BF.SheetPaper2Pooped",
    ["Book_Bible"] = "BF.SheetPaper2Pooped",
    ["Book_Biography"] = "BF.SheetPaper2Pooped",
    ["Book_Business"] = "BF.SheetPaper2Pooped",
    ["Book_Childs"] = "BF.SheetPaper2Pooped",
    ["Book_Cinema"] = "BF.SheetPaper2Pooped",
    ["Book_Classic"] = "BF.SheetPaper2Pooped",
    ["Book_ClassicFiction"] = "BF.SheetPaper2Pooped",
    ["Book_ClassicNonfiction"] = "BF.SheetPaper2Pooped",
    ["Book_Computer"] = "BF.SheetPaper2Pooped",
    ["Book_CrimeFiction"] = "BF.SheetPaper2Pooped",
    ["Book_Fantasy"] = "BF.SheetPaper2Pooped",
    ["Book_Farming"] = "BF.SheetPaper2Pooped",
    ["Book_Fashion"] = "BF.SheetPaper2Pooped",
    ["Book_Fiction"] = "BF.SheetPaper2Pooped",
    ["Book_GeneralNonFiction"] = "BF.SheetPaper2Pooped",
    ["Book_GeneralReference"] = "BF.SheetPaper2Pooped",
    ["Book_Golf"] = "BF.SheetPaper2Pooped",
    ["Book_History"] = "BF.SheetPaper2Pooped",
    ["Book_Horror"] = "BF.SheetPaper2Pooped",
    ["Book_Legal"] = "BF.SheetPaper2Pooped",
    ["Book_LiteraryFiction"] = "BF.SheetPaper2Pooped",
    ["Book_Medical"] = "BF.SheetPaper2Pooped",
    ["Book_Military"] = "BF.SheetPaper2Pooped",
    ["Book_MilitaryHistory"] = "BF.SheetPaper2Pooped",
    ["Book_Music"] = "BF.SheetPaper2Pooped",
    ["Book_Nature"] = "BF.SheetPaper2Pooped",
    ["Book_Occult"] = "BF.SheetPaper2Pooped",
    ["Book_Philosophy"] = "BF.SheetPaper2Pooped",
    ["Book_Policing"] = "BF.SheetPaper2Pooped",
    ["Book_Politics"] = "BF.SheetPaper2Pooped",
    ["Book_Quackery"] = "BF.SheetPaper2Pooped",
    ["Book_Religion"] = "BF.SheetPaper2Pooped",
    ["Book_Rich"] = "BF.SheetPaper2Pooped",
    ["Book_Romance"] = "BF.SheetPaper2Pooped",
    ["Book_SadNonFiction"] = "BF.SheetPaper2Pooped",
    ["Book_SchoolTextbook"] = "BF.SheetPaper2Pooped",
    ["Book_SciFi"] = "BF.SheetPaper2Pooped",
    ["Book_Science"] = "BF.SheetPaper2Pooped",
    ["Book_Sports"] = "BF.SheetPaper2Pooped",
    ["Book_Thriller"] = "BF.SheetPaper2Pooped",
    ["Book_Travel"] = "BF.SheetPaper2Pooped",
    ["Book_Western"] = "BF.SheetPaper2Pooped",
    ["ComicBook"] = "BF.SheetPaper2Pooped",
    ["ComicBook_Retail"] = "BF.SheetPaper2Pooped",
    ["Diary1"] = "BF.SheetPaper2Pooped",
    ["Diary2"] = "BF.SheetPaper2Pooped",
    ["Journal"] = "BF.SheetPaper2Pooped",
    ["Notebook"] = "BF.SheetPaper2Pooped",
    ["Notepad"] = "BF.SheetPaper2Pooped",
    ["Paperback_AdventureNonFiction"] = "BF.SheetPaper2Pooped",
    ["Paperback_Art"] = "BF.SheetPaper2Pooped",
    ["Paperback_Baseball"] = "BF.SheetPaper2Pooped",
    ["Paperback_Bible"] = "BF.SheetPaper2Pooped",
    ["Paperback_Biography"] = "BF.SheetPaper2Pooped",
    ["Paperback_Business"] = "BF.SheetPaper2Pooped",
    ["Paperback_Childs"] = "BF.SheetPaper2Pooped",
    ["Paperback_Cinema"] = "BF.SheetPaper2Pooped",
    ["Paperback_Classic"] = "BF.SheetPaper2Pooped",
    ["Paperback_ClassicFiction"] = "BF.SheetPaper2Pooped",
    ["Paperback_ClassicNonfiction"] = "BF.SheetPaper2Pooped",
    ["Paperback_Computer"] = "BF.SheetPaper2Pooped",
    ["Paperback_Conspiracy"] = "BF.SheetPaper2Pooped",
    ["Paperback_CrimeFiction"] = "BF.SheetPaper2Pooped",
    ["Paperback_Diet"] = "BF.SheetPaper2Pooped",
    ["Paperback_Fantasy"] = "BF.SheetPaper2Pooped",
    ["Paperback_Fashion"] = "BF.SheetPaper2Pooped",
    ["Paperback_Fiction"] = "BF.SheetPaper2Pooped",
    ["Paperback_Golf"] = "BF.SheetPaper2Pooped",
    ["Paperback_Hass"] = "BF.SheetPaper2Pooped",
    ["Paperback_History"] = "BF.SheetPaper2Pooped",
    ["Paperback_Horror"] = "BF.SheetPaper2Pooped",
    ["Paperback_Legal"] = "BF.SheetPaper2Pooped",
    ["Paperback_LiteraryFiction"] = "BF.SheetPaper2Pooped",
    ["Paperback_Medical"] = "BF.SheetPaper2Pooped",
    ["Paperback_Military"] = "BF.SheetPaper2Pooped",
    ["Paperback_MilitaryHistory"] = "BF.SheetPaper2Pooped",
    ["Paperback_Music"] = "BF.SheetPaper2Pooped",
    ["Paperback_Nature"] = "BF.SheetPaper2Pooped",
    ["Paperback_NewAge"] = "BF.SheetPaper2Pooped",
    ["Paperback_Occult"] = "BF.SheetPaper2Pooped",
    ["Paperback_Philosophy"] = "BF.SheetPaper2Pooped",
    ["Paperback_Play"] = "BF.SheetPaper2Pooped",
    ["Paperback_Policing"] = "BF.SheetPaper2Pooped",
    ["Paperback_Politics"] = "BF.SheetPaper2Pooped",
    ["Paperback_Poor"] = "BF.SheetPaper2Pooped",
    ["Paperback_Quackery"] = "BF.SheetPaper2Pooped",
    ["Paperback_Quigley"] = "BF.SheetPaper2Pooped",
    ["Paperback_Relationship"] = "BF.SheetPaper2Pooped",
    ["Paperback_Religion"] = "BF.SheetPaper2Pooped",
    ["Paperback_Rich"] = "BF.SheetPaper2Pooped",
    ["Paperback_Romance"] = "BF.SheetPaper2Pooped",
    ["Paperback_SadNonFiction"] = "BF.SheetPaper2Pooped",
    ["Paperback_Scary"] = "BF.SheetPaper2Pooped",
    ["Paperback_SciFi"] = "BF.SheetPaper2Pooped",
    ["Paperback_Science"] = "BF.SheetPaper2Pooped",
    ["Paperback_SelfHelp"] = "BF.SheetPaper2Pooped",
    ["Paperback_Sexy"] = "BF.SheetPaper2Pooped",
    ["Paperback_Sports"] = "BF.SheetPaper2Pooped",
    ["Paperback_Teens"] = "BF.SheetPaper2Pooped",
    ["Paperback_Thriller"] = "BF.SheetPaper2Pooped",
    ["Paperback_Travel"] = "BF.SheetPaper2Pooped",
    ["Paperback_TrueCrime"] = "BF.SheetPaper2Pooped",
    ["Paperback_Western"] = "BF.SheetPaper2Pooped",
    ["PhotoBook"] = "BF.SheetPaper2Pooped",
}

-- Pooled-category display labels.
BF_WipeCategoryLabel = {
    paper = "ContextMenu_PaperScraps"
}
